export { default as Layout } from "./Layout"
export { default as ProductGallery } from "./ProductGallery"
export { default as ProductInfo } from "./ProductInfo"
export { default as Review } from "./Review"
export { default as ProductCard } from "./ProductCard"
