export { default as Layout } from "./Layout"
export { default as Navbar } from "./Navbar"
export { default as ProductGallery } from "./ProductGallery"
export { default as ProductInfo } from "./ProductInfo"
export { default as ProductDescriptions } from "./ProductDescriptions"
export { default as Reviews } from "./Reviews"
